---
- name: Check 'youtrack_image_version' parameter
  assert:
    that:
      - "youtrack_image_version is defined"
      - "youtrack_image_version | length > 0"
    fail_msg: "parameter 'youtrack_image_version' is missing"

- name: Create systemd unit file
  template:
    src: youtrack.service.j2
    dest: "/etc/systemd/system/{{ youtrack_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Enable youtrack service
    - Restart youtrack service

- name: Pull docker image (for shorter downtimes)
  docker_image:
    name: "{{ youtrack_image_name }}:{{ youtrack_image_version }}"
    source: pull
  notify: Restart youtrack service
