---
- name: Create systemd unit file
  template:
    src: youtrack.service.j2
    dest: "/etc/systemd/system/{{ youtrack_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Enable youtrack service
    - Restart youtrack service
