---
dependency:
  name: galaxy

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ansible-docker-bionic
    box: ubuntu/bionic64
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - 'vm.network "private_network", ip: "192.168.33.74"'

provisioner:
  name: ansible
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3
    hosts:
      all:
        vars:
          youtrack_version_for_tests: 2020.3.888
          youtrack_port_for_tests: 8080

verifier:
  name: ansible
