---
dependency:
  name: galaxy

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: ansible-youtrack-buster
    image: docker.io/borisskert/python3:buster
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
      - debian

provisioner:
  name: ansible
  inventory:
    group_vars:
      docker:
        molecule_docker_environment: true
      debian:
        ansible_python_interpreter: /usr/bin/python3
    hosts:
      all:
        vars:
          youtrack_version_for_tests: 2020.3.888

verifier:
  name: ansible
