---
- name: Verify
  hosts: all

  tasks:
    - name: Should systemd unit file
      stat:
        path: /etc/systemd/system/youtrack.service
      register: systemd_service_file
      failed_when: not systemd_service_file.stat.exists
